apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana-logs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kibana-logs
  template:
    metadata:
      labels:
        app: kibana-logs
    spec:
      containers:
      - name: kibana
        image: kibana:8.10.2
        env:
        - name: ELASTICSEARCH_HOSTS
          value: "http://elasticsearch-logs.default.svc.cluster.local:9200"
        - name: ES_JAVA_OPTS
          value: "-Xms128m -Xmx128m"
        ports:
        - containerPort: 5601
        resources:
          limits:
            memory: "256Mi"
            cpu: "500m"
          requests:
            memory: "128Mi"
            cpu: "100m"
