apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: elasticsearch-statefulset
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elasticsearch-app
  serviceName: "elasticsearch-statefulset"
  template:
    metadata:
      labels:
        app: elasticsearch-app
    spec:
      containers:
      - name: elasticsearch-container
        image: elasticsearch:8.10.2
        env:
        - name: discovery.type
          value: "single-node"
        - name: bootstrap.memory_lock
          value: "true"
        - name: ES_JAVA_OPTS
          value: "-Xms265m -Xmx265m"
        - name: xpack.security.enabled
          value: "false"
        volumeMounts:
        - name: es-data
          mountPath: /tmp/elasticsearch/data
        resources:
          limits:
            memory: "1024Mi"
            cpu: "2"
          requests:
            memory: "128Mi"
            cpu: "500m"
      volumes:
      - name: es-data
        persistentVolumeClaim:
          claimName: es-pvc
