apiVersion: batch/v1
kind: Job
metadata:
  name: mongo-init-job
spec:
  template:
    spec:
      containers:
      - name: mongo-init-container
        image: mongo:5.0.21
        command:
        - /bin/sh
        - -c
        - |
          until mongo --host mongo-0.mongo.default.svc.cluster.local --eval 'printjson(db.runCommand({ping: 1}))' | grep 'ok' >/dev/null; do
            echo "Waiting for MongoDB to be ready..."
            sleep 5
          done
          sleep 20
          RS_STATUS=$(mongo --host mongo-0.mongo.default.svc.cluster.local --eval 'rs.status()')
          if echo "$RS_STATUS" | grep -q '"ok" : 0'; then
            echo "Replica set not initialized. Initializing..."
            mongo --host mongo-0.mongo.default.svc.cluster.local --eval 'rs.initiate(
              {
                  _id: "rs0",
                  members: [
                      {_id: 0, host: "mongo-0.mongo.default.svc.cluster.local:27017"},
                      {_id: 1, host: "mongo-1.mongo.default.svc.cluster.local:27017"},
                      {_id: 2, host: "mongo-2.mongo.default.svc.cluster.local:27017"}
                  ]
              }
            )'
          else
            echo "Replica set already initialized."
          fi
      restartPolicy: OnFailure
