apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-admin-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: django-admin-app
  template:
    metadata:
      labels:
        app: django-admin-app
    spec:
      containers:
      - name: django-admin-container
        image: cinema_admin:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8003
        env:
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: secret-env
              key: CINEMA_POSTGRES_NAME
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: secret-env
              key: CINEMA_POSTGRES_PASSWORD
        - name: POSTGRES_PORT
          valueFrom:
            secretKeyRef:
              name: secret-env
              key: CINEMA_POSTGRES_PORT
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: secret-env
              key: CINEMA_POSTGRES_USER
        envFrom:
        - secretRef:
            name: secret-env
        command: ["gunicorn", "config.asgi:application", "--config", "config/gunicorn_config.py"]
        volumeMounts:
        - mountPath: /app/static
          name: static-volume
        - mountPath: /app/media
          name: media-volume
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
      volumes:
      - name: static-volume
        persistentVolumeClaim:
          claimName: static-pvc
      - name: media-volume
        persistentVolumeClaim:
          claimName: media-pvc
