FROM python:3.10

WORKDIR /src

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

ENV TZ=Europe/Moscow

USER root

COPY requirements.txt requirements.txt

RUN apt-get update && apt-get install -y netcat-traditional

RUN  pip install --upgrade pip
RUN pip install -r requirements.txt --no-cache-dir

COPY . /src